# Generated by Django 5.0.3 on 2024-04-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceTracker', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
